### ISSUE TITLE
deploy_memberNFT.jsの引数

### ISSUE THREAD

**Issue by keisukefunatsu** [realtakahashi/dao4.commons.shiden#21]
npx hardhat run --network localhost scripts/deploy_memberNFT.js
実行時に

backend/scripts/deploy_memberNFT.js 
L18
にaddressの引数がないので適当に追加するのが良いかと
const nft = await NFT.deploy("test", "test", "test.com", "0xAbB12158488d9C9Bd52C14B9AE4C835eCE4A6e13");

**Comment by realtakahashi** [comment]
ご指摘ありがとうございます。
対応してプルリク作成しております。
