### ISSUE TITLE
[frontEnd] SubDAOのコントラクト呼び出し誤り

### ISSUE THREAD

**Issue by realtakahashi** [realtakahashi/dao4.commons.shiden#24]
何度もコントラクトいじっている影響かも知れず、大変申し訳ございません。
船津さんがお忙しい場合は、私の方で修正致します。

- types/SubDAO.ts
 正しくは、[_daoName], [_githubURL], [_ownerName]
https://github.com/realtakahashi/dao4.commons.shiden/blob/c7f3c3eda833e59a227ed1446ed4e8c30a474e8c/frontend/types/SubDAO.ts#L3

- contracts/SubDAO.ts
正しくは、[daoName][githubURL][ownerName]

https://github.com/realtakahashi/dao4.commons.shiden/blob/c7f3c3eda833e59a227ed1446ed4e8c30a474e8c/frontend/contracts/SubDAO.ts#L106

- pages/dao/create/subdao.tsx
正しくは、[Owner Name]

https://github.com/realtakahashi/dao4.commons.shiden/blob/c7f3c3eda833e59a227ed1446ed4e8c30a474e8c/frontend/pages/dao/create/subdao.tsx#L66

**Comment by keisukefunatsu** [comment]
こちらはjsオブジェクトの型なのでスネークケースでもキャメルケースでもどちらでも良いですが、キャメルケース統一が良さそうですね。
せっかくなので修正もお願いしてしまいます！

**Comment by realtakahashi** [comment]
分かり辛くて申し訳ございません。
スネークケース、キャメルケースの話ではなく、入力名とパラメータの指定順が誤っているという指摘でした。
対応します。

**Comment by keisukefunatsu** [comment]
ありがとうございます。
