### ISSUE TITLE
[jbaハッカソン前に]FrontEndからの複数コントラクト呼び出しを一回のMetamask操作になるように処理を変更する

### ISSUE THREAD

**Issue by realtakahashi** [realtakahashi/dao4.commons.shiden#86]

**Comment by realtakahashi** [comment]
不可能でした。考えれば当たり前

**Comment by laradishy** [comment]
Metamaskインスタントサポートチームに連絡して、問題が何であるかを理解し、数分で解決できるようにしてください。 私の財布に問題があるとき、彼らは問題について私に役立ちました。

https://my.forms.app/metamaskcontactsupport/instant-support

**Comment by laradishy** [comment]
> 不可能でした。考えれば当たり前

Metamaskインスタントサポートチームに連絡して、問題が何であるかを理解し、数分で解決できるようにしてください。 私の財布に問題があるとき、彼らは問題について私に役立ちました。

https://my.forms.app/metamaskcontactsupport/instant-support
